[package]
name        = "nats-lens"
version     = "0.1.0"
edition     = "2021"
description = "NATS JetStream delivery guarantee violation detector"
license     = "MIT"
repository  = "https://github.com/biplabku/nats-lens"
homepage    = "https://github.com/biplabku/nats-lens"
documentation = "https://github.com/biplabku/nats-lens"
keywords    = ["nats", "jetstream", "monitoring", "observability", "messaging"]
categories  = ["network-programming", "development-tools"]
readme      = "../../README.md"

[[bin]]
name = "nats-lens"
path = "src/main.rs"

[dependencies]
nats-lens-core  = { version = "0.1.0", path = "../core" }
async-nats      = { workspace = true }
tokio           = { workspace = true }
serde           = { workspace = true }
serde_json      = { workspace = true }
anyhow          = { workspace = true }
tracing         = { workspace = true }
tracing-subscriber = { workspace = true }
futures-util    = { workspace = true }

axum            = "0.7"
clap            = { version = "4", features = ["derive"] }
tower-http      = { version = "0.6", features = ["fs", "cors"] }
tokio-stream    = { version = "0.1", features = ["sync"] }
